# Generated by Django 2.2.13 on 2020-11-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Douban', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='t1',
            table='t1',
        ),
    ]
