# Generated by Django 2.2.13 on 2020-11-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201105_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='stars',
            field=models.CharField(max_length=15),
        ),
    ]
